version: '3.8'
services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: podchat_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser123
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis
    ports:
      - '6379:6379'
volumes:
  mysql-data: